version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
      docker: 18
    commands:
      - echo $USERNAME $PASSWORD
      - docker login partner.registry.abas.sh -u $USERNAME -p $PASSWORD
      - echo "Hello world!"
      - docker-compose up -d
      - docker ps