version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
      docker: 18
    commands:
      - docker login sdp.registry.abas.sh -u $USERNAME -p $PASSWORD
      - docker-compose up -d 
      - sleep 45
      - ./initGradleProperties.sh
      - docker ps
      - ./gradlew checkPreconditions fullInstall --stacktrace
      - ./gradlew instrumentJfopServer verify codeCoverageVerification calculateCodeCoverage
cache:
  paths:
    - '/root/.m2/**/*'
    - ''